/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.views;

import ec.edu.ups.models.Autor;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class ListarAutorView extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarUsuarioView
     */
    private DefaultTableModel modeloAutor;

    public ListarAutorView() {
        initComponents();
        configurarTabla();
    }
    
    public void configurarTabla() {
        modeloAutor = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //evita que se editen las celdas
            }
        };
        modeloAutor.addColumn("Codigo");
        modeloAutor.addColumn("Nombre completo");
        modeloAutor.addColumn("Nacionalidad");
        modeloAutor.addColumn("Año Nacimiento");
        tblAutores.setModel(modeloAutor);
    }

    public void cargarDatos(List<Autor> autores) {
        modeloAutor.setRowCount(0);
        for (Autor autor : autores) {
            Object[] fila = {
                autor.getCodigo(),
                autor.getNombre(),
                autor.getNacionalidad(),
                autor.getAnioNacimiento()
            };
            modeloAutor.addRow(fila);
        }
    }
    
    public void cambiarIdioma(Locale locale){
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        setTitle(bundle.getString("tituloVentanaAutor4"));
        tblAutores.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("colCodigoAutor"));
        tblAutores.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("colNombre"));
        tblAutores.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("colNacionalidad"));
        tblAutores.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("colNacimiento"));

        tblAutores.getTableHeader().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAutores = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Autores");

        tblAutores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAutores);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAutores;
    // End of variables declaration//GEN-END:variables
}
