/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.views;

import ec.edu.ups.models.Prestamo;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class ListarPrestamoView extends javax.swing.JInternalFrame {

    private Locale idiomaActual = new Locale("es","EC");
    /**
     * Creates new form ListarUsuarioView
     */
    private DefaultTableModel modeloPrestamo;
    
    public ListarPrestamoView() {
        initComponents();
        configurarTabla();
    }
    
    public void configurarTabla() {
        modeloPrestamo = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //evita que se editen las celdas
            }
        };
        modeloPrestamo.addColumn("Id");
        modeloPrestamo.addColumn("Libro");
        modeloPrestamo.addColumn("Usuario");
        modeloPrestamo.addColumn("Bibliotecario");
        modeloPrestamo.addColumn("Fecha devolucion");
        modeloPrestamo.addColumn("Devuelto");
        tblPrestamos.setModel(modeloPrestamo);
    }

    public void cargarDatos(List<Prestamo> prestamos) {
        modeloPrestamo.setRowCount(0);
        for (Prestamo prestamo : prestamos) {
            Object[] fila = {
                prestamo.getId(),
                prestamo.getLibro().getTitulo(),
                prestamo.getUsuario().getNombreCompleto(),
                prestamo.getBibliotecario().getNombre(),
                formatearFecha(prestamo.getFechaDevolucion()),
                prestamo.isDevuelto() ? "Si" : "No"
            };
            modeloPrestamo.addRow(fila);
        }
    }
    
    private String formatearFecha(String fecha) {
        String[] partes = fecha.split("/");
        int dia = Integer.parseInt(partes[0]);
        int mes = Integer.parseInt(partes[1]);
        int anio = Integer.parseInt(partes[2]);

        Calendar calendario = Calendar.getInstance();
        calendario.set(anio, mes - 1, dia);
        Date fechaFinal = calendario.getTime();

        String patron = idiomaActual.getLanguage().equals("en") ? "MM/dd/yyyy" : "dd/MM/yyyy";
        SimpleDateFormat formatoSalida = new SimpleDateFormat(patron, idiomaActual);
        return formatoSalida.format(fechaFinal);
    }
    
    public void cambiarIdioma(Locale locale){
        this.idiomaActual = locale;
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        setTitle(bundle.getString("tituloVentanaPrestamo2"));
        tblPrestamos.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("colId"));
        tblPrestamos.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("colLibro"));
        tblPrestamos.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("colUsuario"));
        tblPrestamos.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("colBibliotecario"));
        tblPrestamos.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("colDevolucion"));
        tblPrestamos.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("colDevuelto"));

        tblPrestamos.getTableHeader().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamos = new javax.swing.JTable();

        setBackground(new java.awt.Color(223, 237, 246));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Prestamos");

        jPanel1.setBackground(new java.awt.Color(240, 247, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 204, 227)));

        tblPrestamos.setBackground(new java.awt.Color(240, 247, 251));
        tblPrestamos.setForeground(new java.awt.Color(46, 58, 70));
        tblPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPrestamos.setGridColor(new java.awt.Color(169, 204, 227));
        tblPrestamos.setSelectionBackground(new java.awt.Color(174, 214, 241));
        tblPrestamos.setSelectionForeground(new java.awt.Color(21, 67, 96));
        jScrollPane1.setViewportView(tblPrestamos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPrestamos;
    // End of variables declaration//GEN-END:variables
}
