/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package ec.edu.ups.views;

import ec.edu.ups.models.Usuario;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class ListarUsuarioView extends javax.swing.JInternalFrame {

    private Locale idiomaActual = new Locale("es","EC");
    /**
     * Creates new form ListarUsuarioView
     */
    private DefaultTableModel modeloUsuario;
    
    public ListarUsuarioView() {
        initComponents();
        configurarTabla();
    }
    
    public void configurarTabla() {
        modeloUsuario = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //evita que se editen las celdas
            }
        };
        modeloUsuario.addColumn("Nombre completo");
        modeloUsuario.addColumn("Cedula");
        modeloUsuario.addColumn("Edad");
        modeloUsuario.addColumn("Correo electronico");
        tblUsuarios.setModel(modeloUsuario);
    }

    public void cargarDatos(List<Usuario> usuarios) {
        modeloUsuario.setRowCount(0);
        for (Usuario usuario : usuarios) {
            Object[] fila = {
                usuario.getNombreCompleto(),
                usuario.getCedula(),
                usuario.getEdad(),
                usuario.getCorreoElectronico()
            };
            modeloUsuario.addRow(fila);
        }
    }
    
    public void cambiarIdioma(Locale locale){
        this.idiomaActual = locale;
        ResourceBundle bundle = ResourceBundle.getBundle("ec.edu.ups.biblioteca.i18n.mensajes", locale);
        setTitle(bundle.getString("tituloVentana4"));
        tblUsuarios.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("colNombre"));
        tblUsuarios.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("colCedula"));
        tblUsuarios.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("colEdad"));
        tblUsuarios.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("colCorreo"));

        tblUsuarios.getTableHeader().repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setBackground(new java.awt.Color(223, 237, 246));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de Usuarios");

        jPanel1.setBackground(new java.awt.Color(240, 247, 251));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(169, 204, 227)));

        tblUsuarios.setBackground(new java.awt.Color(240, 247, 251));
        tblUsuarios.setForeground(new java.awt.Color(46, 58, 70));
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUsuarios.setGridColor(new java.awt.Color(169, 204, 227));
        tblUsuarios.setSelectionBackground(new java.awt.Color(174, 214, 241));
        tblUsuarios.setSelectionForeground(new java.awt.Color(21, 67, 96));
        jScrollPane1.setViewportView(tblUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 789, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
